language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

before_script:
  - |
      cargo install --force --git https://github.com/badboy/travis-after-all-rs

script:
  - |
      true

after_success:
  - /home/travis/.cargo/bin/travis-after-all && echo "All fine, let's publish"

notifications:
  email: false
